import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { assessmentType, assessmentData, contactInfo } = body;

    if (!assessmentType || !assessmentData) {
      return NextResponse.json({ error: 'Missing required data' }, { status: 400 });
    }

    // Generate PDF content based on assessment type
    const pdfContent = generatePDFContent(assessmentType, assessmentData, contactInfo);
    
    // For now, return HTML content that can be converted to PDF client-side
    // In production, you'd use a service like Puppeteer or react-pdf
    return NextResponse.json({
      success: true,
      content: pdfContent,
      filename: `${assessmentType}-report-${Date.now()}.pdf`,
    });

  } catch (error) {
    console.error('PDF generation error:', error);
    return NextResponse.json(
      { error: 'Failed to generate report' },
      { status: 500 }
    );
  }
}

function generatePDFContent(assessmentType: string, data: any, contact: any) {
  const companyName = contact?.company_name || 'Your Company';
  const currentDate = new Date().toLocaleDateString();

  switch (assessmentType) {
    case 'lead_score':
      return `
        <div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px;">
          <header style="text-align: center; margin-bottom: 40px; border-bottom: 2px solid #22d3ee; padding-bottom: 20px;">
            <h1 style="color: #000; margin: 0;">Lead Score Analysis Report</h1>
            <p style="color: #666; margin: 10px 0 0 0;">Generated for ${companyName} on ${currentDate}</p>
          </header>
          
          <section style="margin-bottom: 30px;">
            <h2 style="color: #22d3ee; border-left: 4px solid #22d3ee; padding-left: 15px;">Executive Summary</h2>
            <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; margin: 15px 0;">
              <h3 style="color: #000; margin-top: 0;">Overall Lead Score: ${data.score}/100</h3>
              <p>Your website shows ${data.score >= 70 ? 'strong' : data.score >= 40 ? 'moderate' : 'limited'} lead generation potential.</p>
            </div>
          </section>

          <section style="margin-bottom: 30px;">
            <h2 style="color: #22d3ee; border-left: 4px solid #22d3ee; padding-left: 15px;">Key Findings</h2>
            <ul style="line-height: 1.8;">
              ${data.recommendations?.map((rec: string) => `<li>${rec}</li>`).join('') || '<li>Analysis complete</li>'}
            </ul>
          </section>

          <section>
            <h2 style="color: #22d3ee; border-left: 4px solid #22d3ee; padding-left: 15px;">Next Steps</h2>
            <ol style="line-height: 1.8;">
              <li>Review the recommendations above</li>
              <li>Implement high-priority improvements</li>
              <li>Schedule a consultation with our team</li>
              <li>Monitor your lead generation metrics</li>
            </ol>
          </section>

          <footer style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; text-align: center; color: #666;">
            <p>Generated by Maru Online AI Assessment Platform</p>
            <p>Contact us: hello@maruonline.com</p>
          </footer>
        </div>
      `;

    case 'pipeline_leak':
      return `
        <div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px;">
          <header style="text-align: center; margin-bottom: 40px; border-bottom: 2px solid #ef4444; padding-bottom: 20px;">
            <h1 style="color: #000; margin: 0;">Pipeline Leak Analysis Report</h1>
            <p style="color: #666; margin: 10px 0 0 0;">Generated for ${companyName} on ${currentDate}</p>
          </header>
          
          <section style="margin-bottom: 30px;">
            <h2 style="color: #ef4444; border-left: 4px solid #ef4444; padding-left: 15px;">Revenue at Risk</h2>
            <div style="background: #fef2f2; padding: 20px; border-radius: 8px; margin: 15px 0; border-left: 4px solid #ef4444;">
              <h3 style="color: #000; margin-top: 0;">Total Revenue at Risk: $${data.revenueAtRisk?.toLocaleString() || '0'}</h3>
              <p>Stalled Deals: ${data.stalledDeals || 0} | Bottlenecks Detected: ${data.bottlenecks?.length || 0}</p>
            </div>
          </section>

          <section style="margin-bottom: 30px;">
            <h2 style="color: #ef4444; border-left: 4px solid #ef4444; padding-left: 15px;">Recovery Recommendations</h2>
            <ul style="line-height: 1.8;">
              ${data.recommendations?.map((rec: string) => `<li>${rec}</li>`).join('') || '<li>Analysis complete</li>'}
            </ul>
          </section>

          <footer style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; text-align: center; color: #666;">
            <p>Generated by Maru Online AI Assessment Platform</p>
            <p>Contact us: hello@maruonline.com</p>
          </footer>
        </div>
      `;

    default:
      return `
        <div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px;">
          <header style="text-align: center; margin-bottom: 40px;">
            <h1 style="color: #000; margin: 0;">Assessment Report</h1>
            <p style="color: #666; margin: 10px 0 0 0;">Generated for ${companyName} on ${currentDate}</p>
          </header>
          <p>Your assessment results have been processed successfully.</p>
        </div>
      `;
  }
}