import { NextRequest, NextResponse } from 'next/server';
import jsPDF from 'jspdf';

export async function POST(request: NextRequest) {
  try {
    const { type, data } = await request.json();
    
    if (type === 'lead_score') {
      const pdfBuffer = generateLeadScorePDF(data);
      
      return new NextResponse(pdfBuffer, {
        headers: {
          'Content-Type': 'application/pdf',
          'Content-Disposition': 'attachment; filename="lead-score-report.pdf"',
        },
      });
    }
    
    return NextResponse.json({ error: 'Invalid report type' }, { status: 400 });
  } catch (error) {
    console.error('PDF generation error:', error);
    return NextResponse.json({ error: 'Failed to generate PDF' }, { status: 500 });
  }
}

function generateLeadScorePDF(data: any): Buffer {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(20);
  doc.text('Lead Generation Score Report', 20, 30);
  
  // Company info
  doc.setFontSize(12);
  doc.text(`Company: ${data.company_data?.name || 'Unknown'}`, 20, 50);
  doc.text(`Industry: ${data.company_data?.industry || 'Unknown'}`, 20, 60);
  doc.text(`Analysis Date: ${new Date().toLocaleDateString()}`, 20, 70);
  
  // Overall Score
  doc.setFontSize(16);
  doc.text('Overall Score', 20, 90);
  doc.setFontSize(24);
  doc.text(`${data.score}/100`, 20, 105);
  
  // Factor Breakdown
  doc.setFontSize(14);
  doc.text('Score Breakdown:', 20, 125);
  
  doc.setFontSize(12);
  let yPos = 140;
  Object.entries(data.factors).forEach(([key, value]: [string, any]) => {
    const label = key.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
    doc.text(`${label}: ${value}/100`, 20, yPos);
    yPos += 10;
  });
  
  // Recommendations
  doc.setFontSize(14);
  doc.text('Recommendations:', 20, yPos + 10);
  
  doc.setFontSize(10);
  yPos += 25;
  data.recommendations.forEach((rec: string, index: number) => {
    const lines = doc.splitTextToSize(`${index + 1}. ${rec}`, 170);
    doc.text(lines, 20, yPos);
    yPos += lines.length * 5 + 5;
  });
  
  // Footer
  doc.setFontSize(8);
  doc.text('Generated by Maru Online - AI Marketing Solutions', 20, 280);
  doc.text('Contact: hello@maruonline.com', 20, 285);
  
  return Buffer.from(doc.output('arraybuffer'));
}