/**
 * One-time seed: import the legacy static Insights articles into Sanity so the
 * CMS becomes the single source of truth.
 *
 * Run once after creating SANITY_API_WRITE_TOKEN:
 *   SANITY_API_WRITE_TOKEN=... npx tsx scripts/seed-insights.ts
 *
 * Idempotent — uses a deterministic _id per slug (createOrReplace), so re-running
 * updates the same documents rather than duplicating them.
 */
import 'dotenv/config'
import { randomUUID } from 'node:crypto'
import { writeClient } from '../sanity/lib/writeClient'
import { articles, type Section } from '../app/insights/articles'

type PTSpan = { _type: 'span'; _key: string; text: string; marks: string[] }
type PTBlock = {
  _type: 'block'
  _key: string
  style: string
  markDefs: []
  listItem?: 'bullet'
  level?: number
  children: PTSpan[]
}

const key = () => randomUUID().slice(0, 12)

function span(text: string): PTSpan {
  return { _type: 'span', _key: key(), text, marks: [] }
}

function block(style: string, text: string, listItem?: 'bullet'): PTBlock {
  return {
    _type: 'block',
    _key: key(),
    style,
    markDefs: [],
    ...(listItem ? { listItem, level: 1 } : {}),
    children: [span(text)],
  }
}

/** Convert the legacy Section[] content into Portable Text blocks. */
function toPortableText(sections: Section[]): PTBlock[] {
  const out: PTBlock[] = []
  for (const s of sections) {
    switch (s.type) {
      case 'paragraph':
        if (s.text) out.push(block('normal', s.text))
        break
      case 'heading':
        if (s.text) out.push(block('h2', s.text))
        break
      case 'subheading':
        if (s.text) out.push(block('h3', s.text))
        break
      case 'list':
        for (const item of s.items ?? []) out.push(block('normal', item, 'bullet'))
        break
      case 'callout':
        out.push(block('blockquote', [s.label, s.text].filter(Boolean).join(' — ')))
        break
      case 'quote':
        if (s.text) out.push(block('blockquote', s.text))
        if (s.label) out.push(block('normal', s.label))
        break
      case 'divider':
        break
    }
  }
  return out
}

/** "March 2026" → ISO datetime (1st of that month, 09:00 UTC). */
function toIso(monthYear: string): string {
  const d = new Date(`1 ${monthYear} 09:00:00 UTC`)
  return Number.isNaN(d.getTime()) ? new Date().toISOString() : d.toISOString()
}

async function main() {
  if (!process.env.SANITY_API_WRITE_TOKEN) {
    throw new Error('SANITY_API_WRITE_TOKEN is required (Editor token from sanity.io/manage).')
  }
  for (const a of articles) {
    const doc = {
      _id: `insight-${a.slug}`,
      _type: 'post',
      title: a.title,
      slug: { _type: 'slug', current: a.slug },
      category: a.category,
      excerpt: a.excerpt,
      readTime: a.readTime,
      publishedAt: toIso(a.date),
      body: toPortableText(a.content),
      autoGenerated: false,
    }
    await writeClient.createOrReplace(doc)
    console.log(`✓ seeded ${a.slug}`)
  }
  console.log(`\nDone — ${articles.length} articles in Sanity.`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
