import { defineField, defineType } from 'sanity'

export const post = defineType({
  name: 'post',
  title: 'Post',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {
        source: 'title',
        maxLength: 96,
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'string',
      options: {
        list: [
          'Integration',
          'Diagnostic',
          'Compliance',
          'Engagements',
          'Implementation',
          'Sector',
        ].map((c) => ({ title: c, value: c })),
      },
      initialValue: 'Integration',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'excerpt',
      title: 'Excerpt',
      type: 'text',
      rows: 3,
      description: 'Short summary shown on the Insights list and cards.',
    }),
    defineField({
      name: 'readTime',
      title: 'Read time',
      type: 'string',
      description: 'e.g. "7 min read"',
    }),
    defineField({
      name: 'author',
      title: 'Author',
      type: 'reference',
      to: { type: 'author' },
    }),
    defineField({
      name: 'mainImage',
      title: 'Main image',
      type: 'image',
      options: {
        hotspot: true,
      },
    }),
    defineField({
      name: 'publishedAt',
      title: 'Published at',
      type: 'datetime',
    }),
    defineField({
      name: 'body',
      title: 'Body',
      type: 'array',
      of: [
        { type: 'block' },
        {
          type: 'image',
          options: { hotspot: true },
        },
      ],
    }),
    defineField({
        name: 'seoTitle',
        title: 'SEO Title (Meta)',
        type: 'string',
    }),
    defineField({
        name: 'seoDescription',
        title: 'SEO Description (Meta)',
        type: 'text',
    }),
    defineField({
        name: 'focusKeyword',
        title: 'Focus Keyword',
        type: 'string',
    }),
    defineField({
        name: 'ctaReference',
        title: 'Call to Action (Tool Link)',
        type: 'string',
        description: 'URL to the tool you want to promote (e.g. /tools/lead-score)',
    }),
    defineField({
      name: 'sources',
      title: 'Sources',
      type: 'array',
      description: 'Citations the article draws on. Auto-populated for generated posts.',
      of: [
        {
          type: 'object',
          fields: [
            { name: 'title', title: 'Title', type: 'string' },
            { name: 'url', title: 'URL', type: 'url' },
          ],
          preview: {
            select: { title: 'title', subtitle: 'url' },
          },
        },
      ],
    }),
    defineField({
      name: 'autoGenerated',
      title: 'Auto-generated',
      type: 'boolean',
      description: 'True if drafted by the bi-weekly insights bot.',
      initialValue: false,
      readOnly: true,
    }),
  ],
  preview: {
    select: {
      title: 'title',
      author: 'author.name',
      media: 'mainImage',
    },
    prepare(selection) {
      const { author } = selection
      return { ...selection, subtitle: author && `by ${author}` }
    },
  },
})
